export const PROJECTS = [
  {
    slug: 'saas-platforms',
    id: '01',
    num: 1,
    title: 'SaaS Platforms',
    type: 'Web Applications · Dashboards',
    desc: 'End-to-end product design and engineering. From onboarding flows to complex data dashboards — built to retain, convert, and scale.',
    tags: ['Next.js', 'TypeScript', 'Real-time Data', 'Auth Systems'],
    accent: '#0066ff',
    client: 'Velocity Capital',
    industry: 'Fintech / SaaS',
    year: '2024',
    duration: '8 weeks',
    metrics: [
      { value: '+340%', label: 'Conversion Rate' },
      { value: '2.1s',  label: 'Avg Load Time'   },
      { value: '94',    label: 'Lighthouse Score' },
      { value: '$2.4M', label: 'ARR Influenced'   },
    ],
    challenge: 'Velocity Capital had a product that worked — but looked like it didn\'t. Enterprise prospects were disqualifying them in the first 30 seconds based solely on visual credibility. Their onboarding drop-off was 68% and their dashboard buried the metrics that actually mattered to decision-makers.',
    solution: 'We rebuilt the entire product surface from the authentication flow through to the primary dashboard. Real-time data visualisation using WebSockets, a design system with 140+ tokens, and an onboarding sequence that contextualises value within the first 60 seconds of use.',
    outcome: 'Within 90 days of launch, three Fortune 500 conversations had converted to pilots. Onboarding completion jumped to 91%. The founding team closed their Series A 6 weeks later, citing product credibility as a key investor signal.',
  },
  {
    slug: 'luxury-ecommerce',
    id: '02',
    num: 2,
    title: 'Luxury E-Commerce',
    type: 'Premium Retail · DTC Brands',
    desc: 'For brands where presentation is everything. Shopping experiences that match the quality of the product and significantly lift revenue.',
    tags: ['Shopify', '3D Product Views', 'Custom CMS', 'CRO'],
    accent: '#cc8800',
    client: 'Lumière Co',
    industry: 'Luxury Fashion',
    year: '2024',
    duration: '10 weeks',
    metrics: [
      { value: '+218%', label: 'Revenue / Session' },
      { value: '-44%',  label: 'Cart Abandonment'  },
      { value: '4.8★',  label: 'Customer Rating'   },
      { value: '£1.2M', label: 'First Month GMV'   },
    ],
    challenge: 'Lumière Co was selling €2,000 pieces through a template Shopify store that looked like it cost €29/month to build. The brand positioning — ultra-premium Parisian fashion — was being destroyed at the point of purchase. Average order value was suppressed and return rates were climbing because customers felt surprised by what arrived.',
    solution: 'A ground-up Shopify custom theme with 3D product viewers using Three.js, an editorial content system, and a checkout flow re-engineered around luxury conversion psychology. Every interaction — hover states, transitions, typography hierarchy — communicates quality before a single item enters the cart.',
    outcome: 'Revenue per session more than tripled. Cart abandonment dropped 44%. The brand was featured in Vogue Business the month after relaunch. The creative director called it "the first time the website actually represents what we make."',
  },
  {
    slug: 'brand-identities',
    id: '03',
    num: 3,
    title: 'Brand Identities',
    type: 'Visual Identity · Design Systems',
    desc: 'Complete brand systems from concept to launch. Identities that establish authority in competitive markets and scale across every touchpoint.',
    tags: ['Brand Strategy', 'Design System', 'Typography', 'Motion'],
    accent: '#4488ff',
    client: 'Novastride',
    industry: 'B2B SaaS',
    year: '2024',
    duration: '6 weeks',
    metrics: [
      { value: '3×',    label: 'Pricing Power'     },
      { value: '+180%', label: 'Inbound Leads'     },
      { value: '140+',  label: 'Design Tokens'     },
      { value: '12',    label: 'Touchpoints Built' },
    ],
    challenge: 'Novastride was charging $800/month for enterprise workflow software. Their competitors were charging $4,000. The product was genuinely superior — but the brand communicated "startup" while their buyers were CFOs and VPs of Operations who make decisions based on perceived permanence.',
    solution: 'A complete brand overhaul: new naming architecture, a bespoke wordmark system, a primary typeface pairing, a motion language, and a 140-token design system applied across the website, sales deck, proposal templates, email sequences, and product UI.',
    outcome: 'Novastride raised their pricing to $2,800/month immediately after launch with zero churn. Inbound leads increased 180% in 60 days. Their CEO reported that enterprise prospects now assume they\'re the category leader — which they are.',
  },
  {
    slug: 'marketing-sites',
    id: '04',
    num: 4,
    title: 'Marketing Sites',
    type: 'Landing Pages · Lead Generation',
    desc: 'High-converting marketing sites built for growth — engineered with conversion psychology and scroll-triggered storytelling.',
    tags: ['Next.js', 'GSAP', 'Framer Motion', 'SEO'],
    accent: '#00aaff',
    client: 'Quantum Labs',
    industry: 'Deep Tech / AI',
    year: '2024',
    duration: '5 weeks',
    metrics: [
      { value: '+290%', label: 'Demo Requests'     },
      { value: '38s',   label: 'Avg Time on Page'  },
      { value: '91',    label: 'SEO Authority'     },
      { value: '$480K', label: 'Pipeline / Month'  },
    ],
    challenge: 'Quantum Labs had 45 seconds to explain why their AI infrastructure product was worth $80K/year to a technical buyer who was also talking to AWS, Google Cloud, and three VC-backed competitors. Their existing site had a 91% bounce rate and generated 3 demo requests a month.',
    solution: 'A scroll-driven narrative site where every section answers a specific objection in the buyer\'s mind. GSAP-powered animations that reveal technical proof points at the exact moment they\'re needed. Performance-first engineering with a 94 Lighthouse score. An SEO content architecture that captures high-intent technical queries.',
    outcome: 'Demo requests went from 3 to 92 in the first month. Average session time jumped to 38 seconds — a signal that the narrative is holding attention. The site now generates $480K in qualified pipeline per month. Their CMO said it was the highest-ROI investment the company had ever made.',
  },
] as const

export type Project = typeof PROJECTS[number]
export type ProjectSlug = Project['slug']
